/*

Given a string of length n, generate all of its subsequences. 

A subsequence of a given string (sequence) is a string (sequence) that is generated by 
removing zero or more characters from the given string (sequence) without changing its 
order.

Example
	
	Input : inp[] = "abc"
	Output: ["", "c", "b", "bc", "a", "ac", "ab", "abc"]

Constraints
 
  1 < n < 10

*/

#include<iostream>
#include<set>

using namespace std;

void generateSubsequences(char* inp, char* out, int i, int j, set<string>& s) {

	// base case
	if(inp[i] == '\0') {
		out[j] = '\0';
		string str = string(out);
		s.insert(str);
		// cout << out << endl;
		return;
	}

	// recursive case

	// make a decision for the character at the ith index

	// 1. include the character at the ith index in the output subsequence
	out[j] = inp[i];
	generateSubsequences(inp, out, i+1, j+1, s);
	
	// 2. exclude the character at the ith index from the output subsequence
	generateSubsequences(inp, out, i+1, j, s);
}

int main() {

	char inp[] = "abc";
	char out[10];

	set<string> s;

	generateSubsequences(inp, out, 0, 0, s);
		
	for(string subsequence : s) {
		cout << subsequence << endl;
	}

	return 0;
}
